name: Snapshot

on: [push, pull_request]

jobs:
  release:
    name: Publish snapshot to Maven Central
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        id: setup-jdk
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradle build
        run: ./gradlew build
      - name: Publish to Maven Central
        if: success()
        run: ./gradlew publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}